# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source {{cookiecutter.project_slug}} setup.py test

after_success: coveralls

